로그인 기능 구현 완료
EFUB-CLONE-SLACK/SLACK_BACKEND pull request #8
Opened 2022-10-11 09:57 UTC by sunnyineverywhere

### 기능
- 일반 로그인
- 유저 커스텀 어노테이션
- 리프레시 토큰 발급

### Resolves
#6 #1

2022-10-11 10:14 UTC, sunnyineverywhere commented
https://kitty-geno.tistory.com/133

윈도우에 레디스 설치해주셔야 프로젝트 실행됩니다! 또 업데이트된 application.properties 확인 부탁드립니다

2022-11-04 17:14 UTC, siyeonkm commented on src/main/java/web/slack/config/handlers/CustomLoginSuccessHandler.java
> +        String refreshToken = jwtTokenProvider.createRefreshToken(member.getId());
JwtTokenProvider의 createRefreshToken() 코드를 보면
1. 받은 member id로 memberRepository에서 member 찾음
2. 찾은 member의 email을 get함
3. get한 email로 refreshtoken을 생성

근데 사실, successhandler속에서 oAuth2User로 member자체를 찾을 수 있으니까 굳이 이중으로 일하지 말고 그냥 createRefreshToken으로 member.getEmail()을 파라미터로 넘겨주는게 좋을거같아요! 😊

2022-11-04 17:39 UTC, siyeonkm commented on src/main/java/web/slack/controller/MemberController.java
> +    @PostMapping("/login")
저도 잘은 모르지만 여기 함수가 코드가 좀 긴거같아서 좀더 모듈화하면 좋을거같은데 같이해봐욥

2022-11-04 17:46 UTC, siyeonkm commented on src/main/java/web/slack/service/MemberService.java
> +        if(member.isEmpty()){
Optional<> 타입으로 repository에서 entity 꺼내오시는 경우에는 그냥 memberRepository.findByEmail().orElseThrow(() -> new 커스텀에러); 이런식으로 바로 에러처리 가능합니다! 굳이 if else로 member가 null인 상황 에러처리 안해도돼요

2022-11-04 17:48 UTC, siyeonkm requested changes
코멘트 달아놓은거 참고해서 조금만 수정해주세요~! 첫번째 코멘트만 좀 수정해주시고, 함수 좀더 쪼개달라는거는 나중에 같이해요

2022-11-04 17:48 UTC, siyeonkm commented
> 코멘트 달아놓은거 참고해서 조금만 수정해주세요~! 첫번째 코멘트만 좀 수정해주시고, 함수 좀더 쪼개달라는거는 나중에 같이해요

아맞다 3번째두요

2022-11-07 16:25 UTC, merged